services:
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - mynetwork
  auth-api:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    networks:
      - mynetwork
    environment:
      MONGO_URI: mongodb://mongo:27017/authdb
networks:
  mynetwork:
    driver: bridge
volumes:
  mongo_data:
    driver: local